//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentalCarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars
    {
        public int id { get; set; }
        public int typeNumber { get; set; }
        public string currentKM { get; set; }
        public string proper { get; set; }
        public string available { get; set; }
        public string carNumber { get; set; }
    
        public virtual carTypes carTypes { get; set; }
    }
}
