//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentalCarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carTypes()
        {
            this.cars = new HashSet<cars>();
        }
    
        public int id { get; set; }
        public string maker { get; set; }
        public string model { get; set; }
        public int dailyCost { get; set; }
        public int costOfOverdue { get; set; }
        public string year { get; set; }
        public string gear { get; set; }
        public string photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cars> cars { get; set; }
    }
}
